
import { storageService } from './async-storage.service.js'
import { utilService } from './util.service.js'

const STORAGE_KEY = 'monster'

export const monsterService = {
    query,
    getById,
    save,
}
window.cs = monsterService

_createMonsters()

async function query(filterBy = { choice: '' }) {
    var monsters = await storageService.query(STORAGE_KEY)
    if (filterBy.choice === 'smash') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    if (filterBy.choice === 'pass') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    // if (filterBy.price) {
    //     monsters = monsters.filter(monster => monster.price <= filterBy.price)
    // }
    return monsters
}

function getById(monsterId) {
    return storageService.get(STORAGE_KEY, monsterId)
}

async function save(monster) {
    var savedMonster
    if (monster.id) {
        savedMonster = await storageService.put(STORAGE_KEY, monster)
    } else {
        savedMonster = await storageService.post(STORAGE_KEY, monster)
    }
    return savedMonster
}

function _createMonsters() {
    let monsters = utilService.loadFromStorage(STORAGE_KEY)
    if (!monsters || !monsters.length) {
        const monsters = [
            {
                id: '101',
                name: 'Great Jagras',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/l6hgp3tzi1muh5lgdkry.webp',
                sopChoice: null,
            },
            {
                id: '102',
                name: 'Anjanath',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013095/MH-sop/MHW/xvplkxyiyi0df1cnpy1u.webp',
                sopChoice: null,
            },
            {
                id: '103',
                name: 'Barroth',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/mhfb8eyzlqbetgh7q1ha.webp',
                sopChoice: null,
            },
            {
                id: '104',
                name: 'Kulu-Ya-Ku',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013101/MH-sop/MHW/a9urlr2mgt9jyinhwy4b.webp',
                sopChoice: null,
            },
            {
                id: '105',
                name: 'Pukei-Pukei',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012909/MH-sop/MHW/kxq6owy7fxmssiwax2co.webp',
                sopChoice: null,
            },
            {
                id: '106',
                name: 'Jyuratodus',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012986/MH-sop/MHW/fotvajqg5mkfh5msvwcy.webp',
                sopChoice: null,
            },
            {
                id: '107',
                name: 'Tobi-Kadachi',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/v8wrua6tddxrbqahkxrv.webp',
                sopChoice: null,
            },
            {
                id: '108',
                name: 'Rathian',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/jyx3lj72rbdidruvxi18.png',
                sopChoice: null,
            },
            {
                id: '109',
                name: 'Tzitzi-Ya-Ku',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/jasexq3m2achvcwvfc6t.webp',
                sopChoice: null,
            },
            {
                id: '110',
                name: 'Paolumu',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/xwj2uah4qeh1kyafcju3.webp',
                sopChoice: null,
            },
            {
                id: '111',
                name: 'Great Girros',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/ajmmnki2rjdp6jduakvf.webp',
                sopChoice: null,
            },
            {
                id: '112',
                name: 'Radobaan',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/dfxs6j3f8sgj3gmsvcon.webp',
                sopChoice: null,
            },
            {
                id: '113',
                name: 'Legiana',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/ins0iicuvnnw1lpyzt1h.webp',
                sopChoice: null,
            },
            {
                id: '114',
                name: 'Odogaron',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/igetqzbnkpiodoxxcez6.webp',
                sopChoice: null,
            },
            {
                id: '115',
                name: 'Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013108/MH-sop/MHW/piulpaqwogwq29azog36.png',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646492/MH-sop/MHW/zvfmfyc6ad1oaixopqjl.webp',
                sopChoice: null,
            },
            {
                id: '116',
                name: 'Diablos',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012985/MH-sop/MHW/a95a9ltfpcdpyl80cp0l.png',
                sopChoice: null,
            },
            {
                id: '117',
                name: 'Zorah Magdaros',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/han2ifs5llurldmefstx.webp',
                sopChoice: null,
            },
            {
                id: '118',
                name: 'Dodogama',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012993/MH-sop/MHW/lamsoxlxtrqcannr5lym.webp',
                sopChoice: null,
            },
            {
                id: '119',
                name: 'Lavasioth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/hnjqaeimmvihyustejmr.webp',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646480/MH-sop/MHW/nfixvrk5x908dcilkq5m.png',
                sopChoice: null,
            },
            {
                id: '120',
                name: 'Uragaan',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/e65iyogx4li7xvpkv46b.png',
                sopChoice: null,
            },
            {
                id: '121',
                name: 'Azure Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/syajr0imtuonbxgnryv3.webp',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646491/MH-sop/MHW/cwovnyg7m2w7r88sceqv.webp',
                sopChoice: null,
            },
            {
                id: '122',
                name: 'Bazelgeuse',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/ew4jkytjm65lyddlyyhp.webp',
                sopChoice: null,
            },
            {
                id: '123',
                name: 'Black Diablos',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012985/MH-sop/MHW/qvdvhfaarinmu8x6ss8h.webp',
                sopChoice: null,
            },
            {
                id: '124',
                name: 'Kirin',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012960/MH-sop/MHW/s9pj3hws45aefz1vcuae.png',
                sopChoice: null,
            },
            {
                id: '125',
                name: 'Nergigante',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/uqn7ozpidh2udaoqmytt.webp',
                sopChoice: null,
            },
            {
                id: '126',
                name: 'Teostra',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/cnht7gq7yk82l9shmrig.webp',
                sopChoice: null,
            },
            {
                id: '127',
                name: 'Kushala Daora',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/a5fqdohov5kukeb8fgw2.webp',
                sopChoice: null,
            },
            {
                id: '128',
                name: 'Deviljho',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/xi3exxjsyaesds2katbe.webp',
                sopChoice: null,
            },
            {
                id: '129',
                name: 'Pink Rathian',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/uoae27fcmi9kjqiihzhd.webp',
                sopChoice: null,
            },
            {
                id: '130',
                name: 'Vaal Hazak',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012960/MH-sop/MHW/e0okpjmv1wzhazqv9erg.webp',
                sopChoice: null,
            },
            {
                id: '131',
                name: `Xeno'jiiva`,
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012989/MH-sop/MHW/ql1bqgaq6sisaiejifdu.webp',
                sopChoice: null,
            },
            {
                id: '132',
                name: 'Kulve Taroth',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/nw0w0kkxnivbhqijc5up.webp',
                sopChoice: null,
            },
            {
                id: '133',
                name: 'Lunastra',
                game: 'MHW',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/hurdiyanvildk2aygitw.webp',
                sopChoice: null,
            },
            {
                id: '134',
                name: 'Beotodus',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013105/MH-sop/MHW/pl2u9o6bkbvou1wvbzgb.png',
                sopChoice: null,
            },
            {
                id: '135',
                name: 'Banbaro',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013098/MH-sop/MHW/js3ygwa18st2k1qiklog.webp',
                sopChoice: null,
            },
            {
                id: '136',
                name: 'Viper Tobi-Kadachi',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/mepvmk3qprbtnsmajsqh.webp',
                sopChoice: null,
            },
            {
                id: '137',
                name: 'Nightshade Paolumu',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/ormtuuju8p5wkvdsymwh.webp',
                sopChoice: null,
            },
            {
                id: '138',
                name: 'Coral Pukei-Pukei',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/kvcgqe0ytrvehvzuhveo.webp',
                sopChoice: null,
            },
            {
                id: '139',
                name: 'Barioth',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013118/MH-sop/MHW/qxhqiwafpajl3ynra4te.png',
                sopChoice: null,
            },
            {
                id: '140',
                name: 'Nargacuga',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013100/MH-sop/MHW/m0apuqaxytkfjxmd2fhu.webp',
                sopChoice: null,
            },
            {
                id: '141',
                name: 'Glavenus',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013106/MH-sop/MHW/twt3qlrbcuyxwibbugyr.png',
                sopChoice: null,
            },
            {
                id: '142',
                name: 'Tigrex',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012990/MH-sop/MHW/nkyitdngi02celljcvz5.webp',
                sopChoice: null,
            },
            {
                id: '143',
                name: 'Brachydios',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013050/MH-sop/MHW/erzjrkdaefkbjukqgolr.png',
                sopChoice: null,
            },
            {
                id: '144',
                name: 'Shrieking Legiana',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013093/MH-sop/MHW/vfotqevi29eqv7ts3dcr.webp',
                sopChoice: null,
            },
            {
                id: '145',
                name: 'Fulgur Anjanath',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013111/MH-sop/MHW/avv2gvg2vmrbhdlv1gip.png',
                sopChoice: null,
            },
            {
                id: '146',
                name: 'Acidic Glavenus',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/tww0z09k0sjexnlixjci.webp',
                sopChoice: null,
            },
            {
                id: '147',
                name: 'Ebony Odogaron',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013117/MH-sop/MHW/dys7ts7xsowcep1firbp.png',
                sopChoice: null,
            },
            {
                id: '148',
                name: 'Velkhana',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013092/MH-sop/MHW/sxdsqmm1r6b1ebklte6i.webp',
                sopChoice: null,
            },
            {
                id: '149',
                name: 'Seething Bazelgeuse',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012986/MH-sop/MHW/qd5hrkgavfe1p53w9xdj.webp',
                sopChoice: null,
            },
            {
                id: '150',
                name: 'Blackveil Vaal Hazak',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013093/MH-sop/MHW/wbxoqdnz9uqbbmvovbyr.webp',
                sopChoice: null,
            },
            {
                id: '151',
                name: 'Namielle',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013111/MH-sop/MHW/dgvkqv9lv40l7xagpd7g.png',
                sopChoice: null,
            },
            {
                id: '152',
                name: 'Savage Deviljho',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/xqtj3bhkjy1t4ndh1hkm.webp',
                sopChoice: null,
            },
            {
                id: '153',
                name: 'Ruiner Nergigante',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/r31t3rww9190fqs5mfiv.webp',
                sopChoice: null,
            },
            {
                id: '154',
                name: 'Shara Ishvalda',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/jumeo5htrodaj4anw9c7.webp',
                sopChoice: null,
            },
            {
                id: '155',
                name: 'Zinogre',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013095/MH-sop/MHW/ysg6owsche05rzullon6.webp',
                sopChoice: null,
            },
            {
                id: '156',
                name: 'Yian Garuga',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013102/MH-sop/MHW/pttqnio2fsxct7yeqty5.png',
                sopChoice: null,
            },
            {
                id: '157',
                name: 'Scarred Yian Garuga',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/fus12po6ljztznvn4jzo.webp',
                sopChoice: null,
            },
            {
                id: '158',
                name: 'Silver Rathalos',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012990/MH-sop/MHW/teqzantue7ajglld8u2q.webp',
                sopChoice: null,
            },
            {
                id: '159',
                name: 'Gold Rathian',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/cncrjjcdruhimlhltxeq.webp',
                sopChoice: null,
            },
            {
                id: '160',
                name: 'Brute Tigrex',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/qnjiye9lat4fw4sjaock.webp',
                sopChoice: null,
            },
            {
                id: '161',
                name: 'Frostfang Barioth',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/d4o8asprcohsdbko0qdy.png',
                sopChoice: null,
            },
            {
                id: '162',
                name: 'Stygian Zinogre',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/npldbxftkoavh6b5xuos.webp',
                sopChoice: null,
            },
            {
                id: '163',
                name: 'Rajang',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012989/MH-sop/MHW/te6uj5mjpgng3lrp4szu.webp',
                sopChoice: null,
            },
            {
                id: '164',
                name: 'Furious Rajang',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/vlh2zp3xpnsf45a1xozp.webp',
                sopChoice: null,
            },
            {
                id: '165',
                name: 'Raging Brachydios',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013081/MH-sop/MHW/cireabuabscxdunlf7r7.webp',
                sopChoice: null,
            },
            {
                id: '166',
                name: `Safi'jiiva`,
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/d0jptyvj9jsny8m6ogiu.webp',
                sopChoice: null,
            },
            {
                id: '167',
                name: 'Alatreon',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013098/MH-sop/MHW/qzspeltnqeob5ggywgp7.webp',
                sopChoice: null,
            },
            {
                id: '168',
                name: 'Fatalis',
                game: 'MHWIB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013108/MH-sop/MHW/u5mfrqkpcbtqqwiunvp6.png',
                sopChoice: null,
            },
            {
                id: '169',
                name: 'Khezu',
                game: 'MH-Freedom2',
                iconImg: 'https://www.mandatory.gg/wp-content/uploads/mandatory-mhrise-guides-monstres-khezu.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '170',
                name: 'Doshaguma',
                game: 'Wilds',
                iconImg: 'https://www.monsterhunter.com/wilds/assets/img/monster/m_img_02_s.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '171',
                name: 'Ajarakan',
                game: 'Wilds',
                iconImg: 'https://www.monsterhunter.com/wilds/assets/img/monster/m_img_10_s.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '172',
                name: 'Basarios',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/oygyckkh0ivbj4o4dykn.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '173',
                name: 'Cephadrome',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/wjub9yjif8pxf4q0gwm0.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '174',
                name: 'Gendrome',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/q7bsea2y6g47xbxmvb4t.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '175',
                name: 'Gravios',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/orwrrn58u4migotbfm5d.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '176',
                name: 'Gypceros',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/kimdnvp2smptlet83k5w.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '177',
                name: 'Iodrome',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994753/MH-sop/MH1/rbwunvialw4pwc2ouf8p.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '178',
                name: 'Lao-Shan Lung',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/lsprzeh8fuar7rnvwhjq.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '179',
                name: 'Monoblos',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/kiv57ixlvkriicy6qayu.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '180',
                name: 'Plesioth',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/uchwaamzc88hgzbc1ggs.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '181',
                name: 'Velocidrome',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/ja4hj7dav6ifq61iutab.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '182',
                name: 'Yian Kut-Ku',
                game: 'MH1',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/e2jryvnl8ruetrojbery.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '183',
                name: 'Akantor',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994882/MH-sop/MHF2/ybrh2chmulxvo7uptr3n.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '184',
                name: 'Daimyo Hermitaur',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994882/MH-sop/MHF2/e1x3axwzevhyrcunfl2r.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '185',
                name: 'Shogun Ceanataur',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/x0xzqlksqxnxrmbohzlt.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '186',
                name: 'Shen Gaoren',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994878/MH-sop/MHF2/eglcc6uc1wwxebulzc0q.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '187',
                name: 'Bulldrome',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/pr9qrqbwpvtuwv40f2qs.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '188',
                name: 'Congalala',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/uc39sxgzphiwm7ueh4qu.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '189',
                name: 'Blangonga',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/tycocpxfuhuymdhllbhg.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '190',
                name: 'Chameleos',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/eomaj9v5zogvih821qtt.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '191',
                name: 'Crimson Fatalis',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/byjnsvq19ywsi0jnflao.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '192',
                name: 'White Fatalis',
                game: 'MHF2',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/quafbvaahuasua6jmm49.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '193',
                name: 'Ukanlos',
                game: 'MHFU',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730995277/MH-sop/MHFU/a0domssnmkqrzqipfqy8.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '194',
                name: 'Yama Tsukami',
                game: 'MHFU',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730995186/MH-sop/MHFU/wed4uckghnkvz3mpnyov.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '195',
                name: 'Agnaktor',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000451/MH-sop/MH3/stznonckt4dtse7btlr3.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '196',
                name: 'Gigginox',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000450/MH-sop/MH3/xyilvs9bxu6639owsger.webp',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '197',
                name: 'Gobul',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/usnp6x9mxgrcvh5xjdch.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '198',
                name: 'Great Baggi',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000457/MH-sop/MH3/mrnlbi9alvziaonzyjap.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '199',
                name: 'Lagiacrus',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/kpeqb0ixip4lnqisi2yn.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '200',
                name: 'Qurupeco',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000454/MH-sop/MH3/oci4ztpau5rifg5q7il7.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '201',
                name: 'Royal Ludroth',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000456/MH-sop/MH3/vsjkwoldafauzf5alf3a.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '202',
                name: 'Ceadeus',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/zxvdrilkixgi1ruhgham.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '203',
                name: 'Jhen Mohran',
                game: 'MH3',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000459/MH-sop/MH3/sah2rnxwyey5ahyrgitp.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '204',
                name: 'Arzuros',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000741/MH-sop/MH3U/ktehrikq9xtghr2sve0m.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '205',
                name: 'Dire Miralis',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/nureohhebm0h3eacl6if.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '206',
                name: 'Duramboros',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/drwhajg993dqc1ypsemn.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '207',
                name: 'Great Wroggi',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000734/MH-sop/MH3U/bdlfeabytufbnzhfymy9.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '208',
                name: 'Lagombi',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000737/MH-sop/MH3U/k4yj3aktd3sojsika9qo.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '209',
                name: 'Nibelsnarf',
                game: 'MH3U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/stn1ujbyyutisf86m4hk.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '210',
                name: 'Gore Magala',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001394/MH-sop/MH4U/gsjj0bcgkjrfojqllbn5.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '211',
                name: 'Kecha Wacha',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/ewrv8rh6jfzuw6bgmcm3.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '212',
                name: 'Najarala',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/kzx2cpe9urvco4viwnxg.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '213',
                name: 'Nerscylla',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/nbzjehi3qvdkrezs22fq.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '214',
                name: 'Seltas',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/malaj3d5nogfyhlh1sdj.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '215',
                name: 'Seltas Queen',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/uhg6xjolxsid7ocjqf3n.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '216',
                name: 'Seregios',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001109/MH-sop/MH4U/we8xcft4xlngycb42lvk.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '217',
                name: 'Tetsucabra',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001115/MH-sop/MH4U/hrbaolrbqejgujdwdhxq.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '218',
                name: 'Zamtrios',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001106/MH-sop/MH4U/xrczpionduflx3rvuvyd.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '219',
                name: `Dah'ren Mohran`,
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/hkfeyzgmuhfffzzdjpzu.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '220',
                name: 'Dalamadur',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001533/MH-sop/MH4U/vi2bdn7njsnmoekefats.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '221',
                name: 'Gogmazios',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001107/MH-sop/MH4U/ndkebtmj1jxsrc8zuro5.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '222',
                name: 'Shagaru Magala',
                game: 'MH4U',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001107/MH-sop/MH4U/x7finssmggykpyrxpelp.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '223',
                name: 'Astalos',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001334/MH-sop/MHGen/cy8rvq1eka953vyndxqf.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '224',
                name: 'Gammoth',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/ro6xdql2cjvg31fz4ppj.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '225',
                name: 'Great Maccao',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/vxavsn4yvkpp6bwz73ea.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '226',
                name: 'Malfestio',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/jeahrtmdk5fojqujffuh.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '227',
                name: 'Mizutsune',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001339/MH-sop/MHGen/cbdldieglngink9gz33z.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '228',
                name: 'Volvidon',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001342/MH-sop/MHGen/oekffmnszhzplofnle8d.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '229',
                name: 'Amatsu',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001340/MH-sop/MHGen/keznqtfr2ivssbi9acel.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '230',
                name: 'Nakarkos',
                game: 'MHGen',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001336/MH-sop/MHGen/q8mb5xcmynwfxgvfj5rd.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '231',
                name: 'Ahtal-Ka',
                game: 'MHGU',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001896/MH-sop/MHGU/d28lz3nvqnarkqjbdudg.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '232',
                name: 'Valstrax',
                game: 'MHGU',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001898/MH-sop/MHGU/uec1otjivcnhak29snul.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '233',
                name: 'Aknosom',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002072/MH-sop/MHRise/wzvwtojkl8jzue5qpsle.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '234',
                name: 'Almudron',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/ie8p0x7dy4ejtxfqrltx.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '235',
                name: 'Bishaten',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002073/MH-sop/MHRise/artgsyu34a7mkptbihjd.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '236',
                name: 'Goss Harag',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002074/MH-sop/MHRise/jxrwrkexpsvxfby3kvyj.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '237',
                name: 'Magnamalo',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002075/MH-sop/MHRise/ennzuwe4wqevncnaxhp1.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '238',
                name: 'Rakna-Kadaki',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002079/MH-sop/MHRise/rktumx1ymbuij6ilckgg.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '239',
                name: 'Somnacanth',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/nc8vs2196cm5n1avjlt8.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '240',
                name: 'Tetranadon',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002074/MH-sop/MHRise/m8b8jbbvvayjnndwjiqg.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '241',
                name: 'Thunder Serpent Narwa',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002076/MH-sop/MHRise/mmumrhontf7jqpkzxvh3.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '242',
                name: 'Wind Serpent Ibushi',
                game: 'MHRise',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/pkgure0rvmantxaax6it.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '243',
                name: 'Malzeno',
                game: 'MHRiseSB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002429/MH-sop/MHRiseSB/eslu1lapv03a7uerqy32.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '244',
                name: 'Lunagaron',
                game: 'MHRiseSB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002431/MH-sop/MHRiseSB/kjvf2mxdqybqdr0ja61b.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '245',
                name: 'Garangolm',
                game: 'MHRiseSB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002428/MH-sop/MHRiseSB/eaahifw5buy3jjfhi0as.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '246',
                name: 'Espinas',
                game: 'MHRiseSB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002429/MH-sop/MHRiseSB/lcfvyg8qij8q0mhn95ap.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '247',
                name: 'Gaismagorm',
                game: 'MHRiseSB',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002431/MH-sop/MHRiseSB/wco85gi1kfn4mdijbmxq.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '248',
                name: 'Arkveld',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002687/MH-sop/Wilds/r2jpe6a200mppw2zk565.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '249',
                name: 'Rompopolo',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002691/MH-sop/Wilds/npfaifugud7umyjw8rou.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '250',
                name: 'Uth Duna',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002696/MH-sop/Wilds/dufwp6dsrdyhjynfnp8w.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '251',
                name: 'Lala Barina',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002688/MH-sop/Wilds/bz6dqj8g2zaggnfvjamk.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '252',
                name: 'Rey Dau',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002689/MH-sop/Wilds/grgbbyeujjw9xivcxgx7.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '253',
                name: 'Balahara',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002685/MH-sop/Wilds/khyf8a0dufbqnryxltt1.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '254',
                name: 'Quematrice',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002693/MH-sop/Wilds/fhqgtoaey0upw5acpx5y.png',
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '255',
                name: 'Chatacabra',
                game: 'Wilds',
                iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002685/MH-sop/Wilds/y4rgwxibebamiayvrqrh.png',
                sopChoice: null,
                isHidden: true,
            },
        ]
        utilService.saveToStorage(STORAGE_KEY, monsters)
    }
}

// TEST DATA
// storageService.post(STORAGE_KEY, {vendor: 'Subali Rahok 2', price: 980}).then(x => console.log(x))

// finish home page
// add extra monsters 
// add backend