
import { storageService } from './async-storage.service.js'
import { utilService } from './util.service.js'

const STORAGE_KEY = 'monster'

export const monsterService = {
    query,
    getById,
    save,
    resetMonsters,
}
window.cs = monsterService

_createMonsters()

async function query(filterBy = { choice: '' }) {
    var monsters = await storageService.query(STORAGE_KEY)
    if (filterBy.choice === 'smash') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    if (filterBy.choice === 'pass') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    // if (filterBy.price) {
    //     monsters = monsters.filter(monster => monster.price <= filterBy.price)
    // }
    return monsters
}

function getById(monsterId) {
    return storageService.get(STORAGE_KEY, monsterId)
}

async function save(monster) {
    var savedMonster
    if (monster.id) {
        savedMonster = await storageService.put(STORAGE_KEY, monster)
    } else {
        savedMonster = await storageService.post(STORAGE_KEY, monster)
    }
    return savedMonster
}

function resetMonsters() {
    localStorage.clear()
    _createMonsters()
}

function _createMonsters() {
    let monsters = utilService.loadFromStorage(STORAGE_KEY)
    if (!monsters || !monsters.length) {
        const monsters = [
            {
                id: '101',
                name: 'Great Jagras',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/l6hgp3tzi1muh5lgdkry.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057978/SOP-Moms/MHW/hesbhfy8dwiyqf5dip6t.webp',
                sopChoice: null,
            },
            {
                id: '102',
                name: 'Anjanath',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013095/MH-sop/MHW/xvplkxyiyi0df1cnpy1u.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058005/SOP-Moms/MHW/iywnx5u5uhj6loetsndh.webp',
                sopChoice: null,
            },
            {
                id: '103',
                name: 'Barroth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/mhfb8eyzlqbetgh7q1ha.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057981/SOP-Moms/MHW/xyv8kywhzjlwn6uuwtns.webp',
                sopChoice: null,
            },
            {
                id: '104',
                name: 'Kulu-Ya-Ku',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013101/MH-sop/MHW/a9urlr2mgt9jyinhwy4b.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/athdguvo1neh0n9kqgsf.webp',
                sopChoice: null,
            },
            {
                id: '105',
                name: 'Pukei-Pukei',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012909/MH-sop/MHW/kxq6owy7fxmssiwax2co.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057977/SOP-Moms/MHW/rbuanhsziz0f9cj4eg5o.webp',
                sopChoice: null,
            },
            {
                id: '106',
                name: 'Jyuratodus',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012986/MH-sop/MHW/fotvajqg5mkfh5msvwcy.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/qyzd2fj8qczyxpi0euwi.webp',
                sopChoice: null,
            },
            {
                id: '107',
                name: 'Tobi-Kadachi',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/v8wrua6tddxrbqahkxrv.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057998/SOP-Moms/MHW/lzsp8lknji4u6r2cbcpo.webp',
                sopChoice: null,
            },
            {
                id: '108',
                name: 'Rathian',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/jyx3lj72rbdidruvxi18.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057976/SOP-Moms/MHW/maoceki34hmvwrslnafh.png',
                sopChoice: null,
            },
            {
                id: '109',
                name: 'Tzitzi-Ya-Ku',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/jasexq3m2achvcwvfc6t.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057976/SOP-Moms/MHW/jwwbqoiavkjrbu1ge2at.webp',
                sopChoice: null,
            },
            {
                id: '110',
                name: 'Paolumu',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/xwj2uah4qeh1kyafcju3.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058004/SOP-Moms/MHW/giuobzbz7zpnph3v0aoy.webp',
                sopChoice: null,
            },
            {
                id: '111',
                name: 'Great Girros',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/ajmmnki2rjdp6jduakvf.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057960/SOP-Moms/MHW/be4zacrkrrhqp2nvrauz.webp',
                sopChoice: null,
            },
            {
                id: '112',
                name: 'Radobaan',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/dfxs6j3f8sgj3gmsvcon.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057965/SOP-Moms/MHW/qyfrb7kpfej3orexgqxt.webp',
                sopChoice: null,
            },
            {
                id: '113',
                name: 'Legiana',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/ins0iicuvnnw1lpyzt1h.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057974/SOP-Moms/MHW/kfm5khyleouvo1ikwwbt.webp',
                sopChoice: null,
            },
            {
                id: '114',
                name: 'Odogaron',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/igetqzbnkpiodoxxcez6.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057973/SOP-Moms/MHW/xnzsm77ud9laodmgrvcd.webp',
                sopChoice: null,
            },
            {
                id: '115',
                name: 'Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646492/MH-sop/MHW/zvfmfyc6ad1oaixopqjl.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058010/SOP-Moms/MHW/sfjwz2pqkfa5oytrbzxr.webp',
                sopChoice: null,
            },
            {
                id: '116',
                name: 'Diablos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012985/MH-sop/MHW/a95a9ltfpcdpyl80cp0l.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/rwbgkzdorpudj6ocn1yi.png',
                sopChoice: null,
            },
            {
                id: '117',
                name: 'Zorah Magdaros',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/han2ifs5llurldmefstx.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057972/SOP-Moms/MHW/hfqxhbbfoxxud5wvgihm.webp',
                sopChoice: null,
            },
            {
                id: '118',
                name: 'Dodogama',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012993/MH-sop/MHW/lamsoxlxtrqcannr5lym.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057979/SOP-Moms/MHW/ogyc4hkc8k10bt026mh5.webp',
                sopChoice: null,
            },
            {
                id: '119',
                name: 'Lavasioth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646480/MH-sop/MHW/nfixvrk5x908dcilkq5m.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/ueycg8oswn6dfxe78nh7.png',
                sopChoice: null,
            },
            {
                id: '120',
                name: 'Uragaan',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/e65iyogx4li7xvpkv46b.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057968/SOP-Moms/MHW/ea6vs5xhntdmpp7e2az5.png',
                sopChoice: null,
            },
            {
                id: '121',
                name: 'Azure Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730646491/MH-sop/MHW/cwovnyg7m2w7r88sceqv.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057963/SOP-Moms/MHW/nssfzwxfwkthaulngpae.webp',
                sopChoice: null,
            },
            {
                id: '122',
                name: 'Bazelgeuse',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/ew4jkytjm65lyddlyyhp.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/d97vyqog3itfmzglytxp.webp',
                sopChoice: null,
            },
            {
                id: '123',
                name: 'Black Diablos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012985/MH-sop/MHW/qvdvhfaarinmu8x6ss8h.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057990/SOP-Moms/MHW/apm1eh9oyfrpgu596g90.webp',
                sopChoice: null,
            },
            {
                id: '124',
                name: 'Kirin',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012960/MH-sop/MHW/s9pj3hws45aefz1vcuae.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057992/SOP-Moms/MHW/txvwl1fzoicolun7nnwu.png',
                sopChoice: null,
            },
            {
                id: '125',
                name: 'Nergigante',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/uqn7ozpidh2udaoqmytt.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/pxjdchlazs472b2txodc.webp',
                sopChoice: null,
            },
            {
                id: '126',
                name: 'Teostra',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/cnht7gq7yk82l9shmrig.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/wntiugx2ov8dbtly46it.webp',
                sopChoice: null,
            },
            {
                id: '127',
                name: 'Kushala Daora',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/a5fqdohov5kukeb8fgw2.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057960/SOP-Moms/MHW/gh5psmeudul3j3wdnvb6.webp',
                sopChoice: null,
            },
            {
                id: '128',
                name: 'Deviljho',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012992/MH-sop/MHW/xi3exxjsyaesds2katbe.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058001/SOP-Moms/MHW/wabbxaonypsojinftttz.webp',
                sopChoice: null,
            },
            {
                id: '129',
                name: 'Pink Rathian',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012959/MH-sop/MHW/uoae27fcmi9kjqiihzhd.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057996/SOP-Moms/MHW/anrjraqsgdgtavgqhuqa.webp',
                sopChoice: null,
            },
            {
                id: '130',
                name: 'Vaal Hazak',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012960/MH-sop/MHW/e0okpjmv1wzhazqv9erg.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057965/SOP-Moms/MHW/wcttazbpshg2imb3ebjz.webp',
                sopChoice: null,
            },
            {
                id: '131',
                name: `Xeno'jiiva`,
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012989/MH-sop/MHW/ql1bqgaq6sisaiejifdu.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057989/SOP-Moms/MHW/efrpyfsajglmc9ylzxea.webp',
                sopChoice: null,
            },
            {
                id: '132',
                name: 'Kulve Taroth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/nw0w0kkxnivbhqijc5up.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/brgsrb2rnx4owwjbpljn.webp',
                sopChoice: null,
            },
            {
                id: '133',
                name: 'Lunastra',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/hurdiyanvildk2aygitw.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057973/SOP-Moms/MHW/toxsq2pb8oxen4ebqn6j.webp',
                sopChoice: null,
            },
            {
                id: '134',
                name: 'Beotodus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013105/MH-sop/MHW/pl2u9o6bkbvou1wvbzgb.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057993/SOP-Moms/MHW/mzxrrkrkrrrtcwtpq61n.png',
                sopChoice: null,
            },
            {
                id: '135',
                name: 'Banbaro',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013098/MH-sop/MHW/js3ygwa18st2k1qiklog.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057978/SOP-Moms/MHW/knavedswu2olhzlblru6.webp',
                sopChoice: null,
            },
            {
                id: '136',
                name: 'Viper Tobi-Kadachi',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/mepvmk3qprbtnsmajsqh.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057982/SOP-Moms/MHW/upbzrvzom1gdjjlabwhi.webp',
                sopChoice: null,
            },
            {
                id: '137',
                name: 'Nightshade Paolumu',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/ormtuuju8p5wkvdsymwh.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/kzjhv0w9gpuku8outrxo.webp',
                sopChoice: null,
            },
            {
                id: '138',
                name: 'Coral Pukei-Pukei',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/kvcgqe0ytrvehvzuhveo.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057977/SOP-Moms/MHW/khk2so82cm7hglittnv0.webp',
                sopChoice: null,
            },
            {
                id: '139',
                name: 'Barioth',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013118/MH-sop/MHW/qxhqiwafpajl3ynra4te.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058007/SOP-Moms/MHW/wytubvem8knd942ejxnt.png',
                sopChoice: null,
            },
            {
                id: '140',
                name: 'Nargacuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013100/MH-sop/MHW/m0apuqaxytkfjxmd2fhu.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057983/SOP-Moms/MHW/vdryrvuoogu8ljqmz2lo.webp',
                sopChoice: null,
            },
            {
                id: '141',
                name: 'Glavenus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013106/MH-sop/MHW/twt3qlrbcuyxwibbugyr.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/e9yyyf0guuf412qortbl.png',
                sopChoice: null,
            },
            {
                id: '142',
                name: 'Tigrex',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012990/MH-sop/MHW/nkyitdngi02celljcvz5.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057982/SOP-Moms/MHW/euujllqt4z53rrsy6lf9.webp',
                sopChoice: null,
            },
            {
                id: '143',
                name: 'Brachydios',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013050/MH-sop/MHW/erzjrkdaefkbjukqgolr.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/nwmnf0892uxh2hcdlily.png',
                sopChoice: null,
            },
            {
                id: '144',
                name: 'Shrieking Legiana',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013093/MH-sop/MHW/vfotqevi29eqv7ts3dcr.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058000/SOP-Moms/MHW/ieqrjyjmnhg52oq2tdz4.webp',
                sopChoice: null,
            },
            {
                id: '145',
                name: 'Fulgur Anjanath',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013111/MH-sop/MHW/avv2gvg2vmrbhdlv1gip.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/yyv2rt0dis9flofgkiyu.png',
                sopChoice: null,
            },
            {
                id: '146',
                name: 'Acidic Glavenus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012991/MH-sop/MHW/tww0z09k0sjexnlixjci.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/lqhdbqvzqtzjnsd6zkc7.webp',
                sopChoice: null,
            },
            {
                id: '147',
                name: 'Ebony Odogaron',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013117/MH-sop/MHW/dys7ts7xsowcep1firbp.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/ngy0imrfifvag0h6sksx.png',
                sopChoice: null,
            },
            {
                id: '148',
                name: 'Velkhana',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013092/MH-sop/MHW/sxdsqmm1r6b1ebklte6i.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/ilxhepo4wxyqsygjhysw.webp',
                sopChoice: null,
            },
            {
                id: '149',
                name: 'Seething Bazelgeuse',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012986/MH-sop/MHW/qd5hrkgavfe1p53w9xdj.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057990/SOP-Moms/MHW/mjzow5crjzgtpjox8cvu.webp',
                sopChoice: null,
            },
            {
                id: '150',
                name: 'Blackveil Vaal Hazak',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013093/MH-sop/MHW/wbxoqdnz9uqbbmvovbyr.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058001/SOP-Moms/MHW/d7pvixjwxwkl0lssgzfa.webp',
                sopChoice: null,
            },
            {
                id: '151',
                name: 'Namielle',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013111/MH-sop/MHW/dgvkqv9lv40l7xagpd7g.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057967/SOP-Moms/MHW/zhr1m5l0edn4rskwaxpy.png',
                sopChoice: null,
            },
            {
                id: '152',
                name: 'Savage Deviljho',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/xqtj3bhkjy1t4ndh1hkm.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/i2b5fjeuyb675ig7ecz6.webp',
                sopChoice: null,
            },
            {
                id: '153',
                name: 'Ruiner Nergigante',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013096/MH-sop/MHW/r31t3rww9190fqs5mfiv.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057993/SOP-Moms/MHW/ilkjbfxyqmnod4avbaim.webp',
                sopChoice: null,
            },
            {
                id: '154',
                name: 'Shara Ishvalda',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/jumeo5htrodaj4anw9c7.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057979/SOP-Moms/MHW/spnsvsun3fbdrffz9g2b.webp',
                sopChoice: null,
            },
            {
                id: '155',
                name: 'Zinogre',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013095/MH-sop/MHW/ysg6owsche05rzullon6.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058007/SOP-Moms/MHW/z7qy3tc9wxkbnu8hidha.webp',
                sopChoice: null,
            },
            {
                id: '156',
                name: 'Yian Garuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cl oudinary.com/dlnkzbe0y/image/upload/v1729013102/MH-sop/MHW/pttqnio2fsxct7yeqty5.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057989/SOP-Moms/MHW/yxvrneumy2mui8t5j8ae.png',
                sopChoice: null,
            },
            {
                id: '157',
                name: 'Scarred Yian Garuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012984/MH-sop/MHW/fus12po6ljztznvn4jzo.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057974/SOP-Moms/MHW/tlg3eozc2cdgbj9j5stb.webp',
                sopChoice: null,
            },
            {
                id: '158',
                name: 'Silver Rathalos',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012990/MH-sop/MHW/teqzantue7ajglld8u2q.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/fpvvwbdvd9ao24tp6onj.webp',
                sopChoice: null,
            },
            {
                id: '159',
                name: 'Gold Rathian',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/cncrjjcdruhimlhltxeq.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/azxfpafejevzmmrnf9hb.webp',
                sopChoice: null,
            },
            {
                id: '160',
                name: 'Brute Tigrex',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/qnjiye9lat4fw4sjaock.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057991/SOP-Moms/MHW/loslczts8ctv4p7uctps.webp',
                sopChoice: null,
            },
            {
                id: '161',
                name: 'Frostfang Barioth',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012987/MH-sop/MHW/d4o8asprcohsdbko0qdy.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057964/SOP-Moms/MHW/wp2huq6rzldzx70k3f5w.png',
                sopChoice: null,
            },
            {
                id: '162',
                name: 'Stygian Zinogre',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012958/MH-sop/MHW/npldbxftkoavh6b5xuos.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/xlkvbqvo4i0yatld96sb.webp',
                sopChoice: null,
            },
            {
                id: '163',
                name: 'Rajang',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012989/MH-sop/MHW/te6uj5mjpgng3lrp4szu.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057994/SOP-Moms/MHW/aur27oc6plg7zj5jlhcf.webp',
                sopChoice: null,
            },
            {
                id: '164',
                name: 'Furious Rajang',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012982/MH-sop/MHW/vlh2zp3xpnsf45a1xozp.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057999/SOP-Moms/MHW/p9nujmgumpcewsmpafcg.webp',
                sopChoice: null,
            },
            {
                id: '165',
                name: 'Raging Brachydios',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013081/MH-sop/MHW/cireabuabscxdunlf7r7.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057971/SOP-Moms/MHW/fa6qspumfe0pahh09ktw.webp',
                sopChoice: null,
            },
            {
                id: '166',
                name: `Safi'jiiva`,
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729012988/MH-sop/MHW/d0jptyvj9jsny8m6ogiu.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057963/SOP-Moms/MHW/arhdnutwae4rkwrxyyql.webp',
                sopChoice: null,
            },
            {
                id: '167',
                name: 'Alatreon',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013098/MH-sop/MHW/qzspeltnqeob5ggywgp7.webp',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057991/SOP-Moms/MHW/wrvn67srvuvl9ca4l1yc.webp',
                sopChoice: null,
            },
            {
                id: '168',
                name: 'Fatalis',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dlnkzbe0y/image/upload/v1729013108/MH-sop/MHW/u5mfrqkpcbtqqwiunvp6.png',
                iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058004/SOP-Moms/MHW/ouahwwgt374inslgv60j.png',
                sopChoice: null,
            },
            {
                id: '169',
                name: "Malfestio",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/jeahrtmdk5fojqujffuh.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052757/SOP-Moms/MHGen/jjfbpod2jaltsfslk940.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '170',
                name: "Rey Dau",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002689/MH-sop/Wilds/grgbbyeujjw9xivcxgx7.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052801/SOP-Moms/Wilds/ytnndxnkgrj3pnlfwjlp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '171',
                name: "Ahtal-Ka",
                game: "MHGU",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001896/MH-sop/MHGU/d28lz3nvqnarkqjbdudg.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052786/SOP-Moms/MHGU/o1nbdnecmrupyda8yqtv.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '172',
                name: "Shen Gaoren",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994878/MH-sop/MHF2/eglcc6uc1wwxebulzc0q.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052779/SOP-Moms/MHF2/qhvxjndrtlrsj6mfy8jc.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '173',
                name: "Arkveld",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002687/MH-sop/Wilds/r2jpe6a200mppw2zk565.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052803/SOP-Moms/Wilds/wiwjvv76zvrb3qk23lma.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '174',
                name: "Nibelsnarf",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/stn1ujbyyutisf86m4hk.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052748/SOP-Moms/MH3U/v7fbuppv6dv6dobo0ltj.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '175',
                name: "Ceadeus",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/zxvdrilkixgi1ruhgham.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052749/SOP-Moms/MH3/pev2mhelb6ncjzjmelpp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '176',
                name: "Lala Barina",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002688/MH-sop/Wilds/bz6dqj8g2zaggnfvjamk.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052802/SOP-Moms/Wilds/v7ehwfh47d2k9denok6m.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '177',
                name: "Royal Ludroth",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000456/MH-sop/MH3/vsjkwoldafauzf5alf3a.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH3/kkal9ju4nmjlml0ukbri.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '178',
                name: "Shogun Ceanataur",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/x0xzqlksqxnxrmbohzlt.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052755/SOP-Moms/MHF2/hwxzcbumovyso8ju9y8j.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '179',
                name: "Congalala",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/uc39sxgzphiwm7ueh4qu.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052755/SOP-Moms/MHF2/hisnjffnryxjlu6qrwjp.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '180',
                name: "Lao-Shan Lung",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/lsprzeh8fuar7rnvwhjq.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/bgqsvg8y43eia62vwwqd.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '181',
                name: "Cephadrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/wjub9yjif8pxf4q0gwm0.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052742/SOP-Moms/MH1/u6cknsflsrhbp73jdjta.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '182',
                name: "Basarios",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/oygyckkh0ivbj4o4dykn.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/kswobtmjvdckihlalopu.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '183',
                name: "Duramboros",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/drwhajg993dqc1ypsemn.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052749/SOP-Moms/MH3U/udpfnkmxd8zg4yvshso2.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '184',
                name: "Chameleos",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/eomaj9v5zogvih821qtt.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052782/SOP-Moms/MHF2/dh0iqekcbzlw7qx78eg1.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '185',
                name: "Dalamadur",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001533/MH-sop/MH4U/vi2bdn7njsnmoekefats.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052784/SOP-Moms/MH4U/ounhphrw7qtgfi5udqup.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '186',
                name: "Mizutsune",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001339/MH-sop/MHGen/cbdldieglngink9gz33z.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052790/SOP-Moms/MHGen/hlfjaiodl1dwrcv5zlu9.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '187',
                name: "Dah'ren Mohran",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/hkfeyzgmuhfffzzdjpzu.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052774/SOP-Moms/MH4U/ibzgawyuic9e0rfqh06h.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '188',
                name: "Malzeno",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002429/MH-sop/MHRiseSB/eslu1lapv03a7uerqy32.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052763/SOP-Moms/MHRiseSB/wgpmd06lgqi6wrvznbms.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '189',
                name: "Tetranadon",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002074/MH-sop/MHRise/m8b8jbbvvayjnndwjiqg.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052794/SOP-Moms/MHRise/m8wky6nbl6fwgsnclqzq.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '190',
                name: "Espinas",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002429/MH-sop/MHRiseSB/lcfvyg8qij8q0mhn95ap.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRiseSB/gkd6d4xjreafb4hmc1c5.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '191',
                name: "Seltas",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/malaj3d5nogfyhlh1sdj.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH4U/nxbgtqykaivjxojeb4tp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '192',
                name: "Magnamalo",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002075/MH-sop/MHRise/ennzuwe4wqevncnaxhp1.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052790/SOP-Moms/MHRise/x1g3dxfxkn7hoekz2rgj.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '193',
                name: "Gammoth",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/ro6xdql2cjvg31fz4ppj.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052758/SOP-Moms/MHGen/wtjxdkimpdeme5ynezaj.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '194',
                name: "Astalos",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001334/MH-sop/MHGen/cy8rvq1eka953vyndxqf.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052761/SOP-Moms/MHGen/ms0uergz6ylsykgexiyf.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '195',
                name: "Garangolm",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002428/MH-sop/MHRiseSB/eaahifw5buy3jjfhi0as.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052796/SOP-Moms/MHRiseSB/nch0seunba9oam6lgdjm.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '196',
                name: "Nerscylla",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001104/MH-sop/MH4U/nbzjehi3qvdkrezs22fq.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH4U/pgq3aswb2khn2jyvfazt.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '197',
                name: "Yian Kut-Ku",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/e2jryvnl8ruetrojbery.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/mgbssmtcluglrzki86qa.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '198',
                name: "Gobul",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/usnp6x9mxgrcvh5xjdch.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052746/SOP-Moms/MH3/bwktsexlynxhcg22s48c.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '199',
                name: "Iodrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994753/MH-sop/MH1/rbwunvialw4pwc2ouf8p.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/o3czljzqej5ryacqbtoq.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '200',
                name: "Ajarakan",
                game: "Wilds",
                // iconImg: "https://www.monsterhunter.com/wilds/assets/img/monster/m_img_10_s.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052806/SOP-Moms/Wilds/p6m5fyldumgxf8thkusk.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '201',
                name: "Lagombi",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000737/MH-sop/MH3U/k4yj3aktd3sojsika9qo.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052783/SOP-Moms/MH3U/f6ibq3cy2ysruslwveum.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '202',
                name: "Crimson Fatalis",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/byjnsvq19ywsi0jnflao.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052780/SOP-Moms/MHF2/vpkwtw8nv3aptrkqsd8l.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '203',
                name: "Seltas Queen",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/uhg6xjolxsid7ocjqf3n.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052752/SOP-Moms/MH4U/qkrhvrmtjggoqtpnsdw5.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '204',
                name: "Akantor",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994882/MH-sop/MHF2/ybrh2chmulxvo7uptr3n.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052764/SOP-Moms/MHF2/wssq7zknnlgscjyhd0hs.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '205',
                name: "Seregios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001109/MH-sop/MH4U/we8xcft4xlngycb42lvk.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MH4U/s42sse6xhvyhffzq0mg4.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '206',
                name: "Quematrice",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002693/MH-sop/Wilds/fhqgtoaey0upw5acpx5y.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/Wilds/vszjgbtrsufquj0b5oag.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '207',
                name: "Plesioth",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/uchwaamzc88hgzbc1ggs.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/i1ny8ywc8n4tmtvurrcy.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '208',
                name: "Goss Harag",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002074/MH-sop/MHRise/jxrwrkexpsvxfby3kvyj.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052793/SOP-Moms/MHRise/gdvuxveoibbufcjd3le2.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '209',
                name: "Daimyo Hermitaur",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994882/MH-sop/MHF2/e1x3axwzevhyrcunfl2r.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052782/SOP-Moms/MHF2/vzicspwqdpeydjaalvai.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '210',
                name: "Valstrax",
                game: "MHGU",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001898/MH-sop/MHGU/uec1otjivcnhak29snul.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHGU/hgxjqbrc8e3aderi6wvt.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '211',
                name: "Great Wroggi",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000734/MH-sop/MH3U/bdlfeabytufbnzhfymy9.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/MH3U/odmsedq7greirs9zvy85.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '212',
                name: "Gore Magala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001394/MH-sop/MH4U/gsjj0bcgkjrfojqllbn5.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052753/SOP-Moms/MH4U/aejzozhqbbxjdlgfrkvw.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '213',
                name: "Jhen Mohran",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000459/MH-sop/MH3/sah2rnxwyey5ahyrgitp.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052766/SOP-Moms/MH3/oczzktsbwtmliv7vkffo.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '214',
                name: "Blangonga",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/tycocpxfuhuymdhllbhg.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MHF2/dmrr3d1rqfkcpqvrlsvv.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '215',
                name: "Ukanlos",
                game: "MHFU",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730995277/MH-sop/MHFU/a0domssnmkqrzqipfqy8.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052756/SOP-Moms/MHFU/wb7ghfb0s2m5u48x0nxp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '216',
                name: "Gypceros",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/kimdnvp2smptlet83k5w.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052745/SOP-Moms/MH1/cz11lv7rn1mrhlest73s.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '217',
                name: "Shagaru Magala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001107/MH-sop/MH4U/x7finssmggykpyrxpelp.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052779/SOP-Moms/MH4U/evrd3jdpy25rbbnpjrkm.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '218',
                name: "Monoblos",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/kiv57ixlvkriicy6qayu.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052743/SOP-Moms/MH1/d30iwllbvspdowfahest.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '219',
                name: "Najarala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/kzx2cpe9urvco4viwnxg.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/MH4U/oggfpvv1pelgajzxivrm.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '220',
                name: "Balahara",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002685/MH-sop/Wilds/khyf8a0dufbqnryxltt1.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/Wilds/ekiux7o9plnvjkcfet79.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '221',
                name: "Gogmazios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001107/MH-sop/MH4U/ndkebtmj1jxsrc8zuro5.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052752/SOP-Moms/MH4U/oka1o180i8ohujaibm6v.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '222',
                name: "Velocidrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/ja4hj7dav6ifq61iutab.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052743/SOP-Moms/MH1/rgsvas5wf46gfa2lx2ep.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '223',
                name: "Gigginox",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000450/MH-sop/MH3/xyilvs9bxu6639owsger.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH3/pdccbyqlh3d7dmmcobdz.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '224',
                name: "Zamtrios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001106/MH-sop/MH4U/xrczpionduflx3rvuvyd.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052753/SOP-Moms/MH4U/tcinu1t9u3ofnpw8xdvr.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '225',
                name: "Gravios",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993930/MH-sop/MH1/orwrrn58u4migotbfm5d.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/mlwoirjd90jorwltbpws.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '226',
                name: "Amatsu",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001340/MH-sop/MHGen/keznqtfr2ivssbi9acel.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052789/SOP-Moms/MHGen/dykatxsd6uk03jhdwtsj.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '227',
                name: "Gaismagorm",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002431/MH-sop/MHRiseSB/wco85gi1kfn4mdijbmxq.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052768/SOP-Moms/MHRiseSB/zfcsywvgpz0k1nu5nfil.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '228',
                name: "Great Baggi",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000457/MH-sop/MH3/mrnlbi9alvziaonzyjap.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052760/SOP-Moms/MH3/k3b3bbiku6fkfkz4pyl8.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '229',
                name: "Somnacanth",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/nc8vs2196cm5n1avjlt8.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052793/SOP-Moms/MHRise/cxkdr94ojuwzh3rpo7qm.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '230',
                name: "Volvidon",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001342/MH-sop/MHGen/oekffmnszhzplofnle8d.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052770/SOP-Moms/MHGen/f35tyblpuzoxotdhimqh.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '231',
                name: "Nakarkos",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001336/MH-sop/MHGen/q8mb5xcmynwfxgvfj5rd.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052784/SOP-Moms/MHGen/sliiftoydfrkshxhcf0n.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '232',
                name: "Thunder Serpent Narwa",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002076/MH-sop/MHRise/mmumrhontf7jqpkzxvh3.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRise/yahop7fishfifowdrphs.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '233',
                name: "Qurupeco",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000454/MH-sop/MH3/oci4ztpau5rifg5q7il7.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052746/SOP-Moms/MH3/f9izcy0bgmttvfru3mv8.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '234',
                name: "Aknosom",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002072/MH-sop/MHRise/wzvwtojkl8jzue5qpsle.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052787/SOP-Moms/MHRise/xaebbowqsmnw4ipwrsyv.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '235',
                name: "Bishaten",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002073/MH-sop/MHRise/artgsyu34a7mkptbihjd.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052763/SOP-Moms/MHRise/untg12k5ei7kz064hxn8.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '236',
                name: "Khezu",
                game: "MHF2",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740090050/SOP-Moms/MHF2/atlupfoap6jyybybcmel.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '237',
                name: "Lunagaron",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002431/MH-sop/MHRiseSB/kjvf2mxdqybqdr0ja61b.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRiseSB/mgzdtkrtvkrwww8qlpb7.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '238',
                name: "Agnaktor",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000451/MH-sop/MH3/stznonckt4dtse7btlr3.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH3/zt6obchnxewoedqprmie.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '239',
                name: "Almudron",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/ie8p0x7dy4ejtxfqrltx.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052764/SOP-Moms/MHRise/nt4t71bdyzlpv3jfyjng.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '240',
                name: "Bulldrome",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994880/MH-sop/MHF2/pr9qrqbwpvtuwv40f2qs.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MHF2/yrotqh27n0ckrmgrxsnq.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '241',
                name: "White Fatalis",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730994879/MH-sop/MHF2/quafbvaahuasua6jmm49.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052780/SOP-Moms/MHF2/efcvhzjogjucbzrgkpbe.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '242',
                name: "Kecha Wacha",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001105/MH-sop/MH4U/ewrv8rh6jfzuw6bgmcm3.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052751/SOP-Moms/MH4U/ukpelc3aszatrizomhdg.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '243',
                name: "Doshaguma",
                game: "Wilds",
                // iconImg: "https://www.monsterhunter.com/wilds/assets/img/monster/m_img_02_s.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052797/SOP-Moms/Wilds/eahkrjzuiybe1mmyvm3v.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '244',
                name: "Rakna-Kadaki",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002079/MH-sop/MHRise/rktumx1ymbuij6ilckgg.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHRise/he9h8xasox08n1wka52l.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '245',
                name: "Lagiacrus",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000452/MH-sop/MH3/kpeqb0ixip4lnqisi2yn.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052748/SOP-Moms/MH3/xq67wlyoinm9ekcjeean.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '246',
                name: "Rompopolo",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002691/MH-sop/Wilds/npfaifugud7umyjw8rou.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052802/SOP-Moms/Wilds/ll1mzqn8tsokt8hffl99.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '247',
                name: "Arzuros",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000741/MH-sop/MH3U/ktehrikq9xtghr2sve0m.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052771/SOP-Moms/MH3U/nhjlgvwhhp1co7vkuydn.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '248',
                name: "Dire Miralis",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731000731/MH-sop/MH3U/nureohhebm0h3eacl6if.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MH3U/hpgqyr4knjmz9fahdmwi.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '249',
                name: "Tetsucabra",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001115/MH-sop/MH4U/hrbaolrbqejgujdwdhxq.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MH4U/xcefmdipaymmwzpmylxl.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '250',
                name: "Great Maccao",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731001333/MH-sop/MHGen/vxavsn4yvkpp6bwz73ea.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052783/SOP-Moms/MHGen/dxbqjiwsp0yae3ocwovy.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '251',
                name: "Yama Tsukami",
                game: "MHFU",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730995186/MH-sop/MHFU/wed4uckghnkvz3mpnyov.webp",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052758/SOP-Moms/MHFU/wqdiq9dqksqnwck5msuu.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '252',
                name: "Gendrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1730993929/MH-sop/MH1/q7bsea2y6g47xbxmvb4t.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/ceq6xot9cpso1vosbpkd.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '253',
                name: "Uth Duna",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002696/MH-sop/Wilds/dufwp6dsrdyhjynfnp8w.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/Wilds/qsv4ydjxlthntbdznota.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '254',
                name: "Chatacabra",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002685/MH-sop/Wilds/y4rgwxibebamiayvrqrh.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052797/SOP-Moms/Wilds/cbpsb0lg0vedebhai5hl.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '255',
                name: "Wind Serpent Ibushi",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dlnkzbe0y/image/upload/v1731002078/MH-sop/MHRise/pkgure0rvmantxaax6it.png",
                iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHRise/lpwhdeotfvtrolycbso9.png",
                sopChoice: null,
                isHidden: true,
            },
        ]
        utilService.saveToStorage(STORAGE_KEY, monsters)
    }
}

// TEST DATA
// storageService.post(STORAGE_KEY, {vendor: 'Subali Rahok 2', price: 980}).then(x => console.log(x))

// add imaage loader?
// change extra challenge css?
// test site 
