
import { storageService } from './async-storage.service.js'
import { utilService } from './util.service.js'

const STORAGE_KEY = 'monster'

export const monsterService = {
    query,
    getById,
    save,
    resetMonsters,
}
window.cs = monsterService

_createMonsters()

async function query(filterBy = { choice: '' }) {
    var monsters = await storageService.query(STORAGE_KEY)
    if (filterBy.choice === 'smash') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    if (filterBy.choice === 'pass') {
        const regex = new RegExp(filterBy.choice, 'i')
        monsters = monsters.filter(monster => regex.test(monster.sopChoice))
    }
    // if (filterBy.price) {
    //     monsters = monsters.filter(monster => monster.price <= filterBy.price)
    // }
    return monsters
}

function getById(monsterId) {
    return storageService.get(STORAGE_KEY, monsterId)
}

async function save(monster) {
    var savedMonster
    if (monster.id) {
        savedMonster = await storageService.put(STORAGE_KEY, monster)
    } else {
        savedMonster = await storageService.post(STORAGE_KEY, monster)
    }
    return savedMonster
}

function resetMonsters() {
    localStorage.clear()
    _createMonsters()
}

function _createMonsters() {
    let monsters = utilService.loadFromStorage(STORAGE_KEY)
    if (!monsters || !monsters.length) {
        const monsters = [
            {
                id: '101',
                name: 'Great Jagras',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057978/SOP-Moms/MHW/hesbhfy8dwiyqf5dip6t.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130477/MHW/mdngvlv0lknhhkk0pqns.webp',
                sopChoice: null,
            },
            {
                id: '102',
                name: 'Anjanath',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058005/SOP-Moms/MHW/iywnx5u5uhj6loetsndh.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130504/MHW/huvkces1vhx5nkkke3oe.webp',
                sopChoice: null,
            },
            {
                id: '103',
                name: 'Barroth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057981/SOP-Moms/MHW/xyv8kywhzjlwn6uuwtns.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130479/MHW/qvffe0jihdn391lig3tm.webp',
                sopChoice: null,
            },
            {
                id: '104',
                name: 'Kulu-Ya-Ku',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/athdguvo1neh0n9kqgsf.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130461/MHW/b6bzhv3t5bmmorughemn.webp',
                sopChoice: null,
            },
            {
                id: '105',
                name: 'Pukei-Pukei',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057977/SOP-Moms/MHW/rbuanhsziz0f9cj4eg5o.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130476/MHW/u2krfboljzqpbw0zgsau.webp',
                sopChoice: null,
            },
            {
                id: '106',
                name: 'Jyuratodus',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/qyzd2fj8qczyxpi0euwi.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130468/MHW/ditfdigsk7vamuky6skj.webp',
                sopChoice: null,
            },
            {
                id: '107',
                name: 'Tobi-Kadachi',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057998/SOP-Moms/MHW/lzsp8lknji4u6r2cbcpo.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130499/MHW/dm7fhpci7yzobfud5qex.webp',
                sopChoice: null,
            },
            {
                id: '108',
                name: 'Rathian',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057976/SOP-Moms/MHW/maoceki34hmvwrslnafh.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130476/MHW/j8eio9ernuea9k2ptqql.png',
                sopChoice: null,
            },
            {
                id: '109',
                name: 'Tzitzi-Ya-Ku',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057976/SOP-Moms/MHW/jwwbqoiavkjrbu1ge2at.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130474/MHW/zkd3anbhbdv6ywj4h6zn.webp',
                sopChoice: null,
            },
            {
                id: '110',
                name: 'Paolumu',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058004/SOP-Moms/MHW/giuobzbz7zpnph3v0aoy.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130502/MHW/gh9liadtugpwie37nyf7.webp',
                sopChoice: null,
            },
            {
                id: '111',
                name: 'Great Girros',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057960/SOP-Moms/MHW/be4zacrkrrhqp2nvrauz.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130460/MHW/uveickvh1bpoap0nfy2d.webp',
                sopChoice: null,
            },
            {
                id: '112',
                name: 'Radobaan',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057965/SOP-Moms/MHW/qyfrb7kpfej3orexgqxt.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130463/MHW/evpkbeplhpt71hluarx0.webp',
                sopChoice: null,
            },
            {
                id: '113',
                name: 'Legiana',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057974/SOP-Moms/MHW/kfm5khyleouvo1ikwwbt.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130472/MHW/yw3ezhvsh4nfytde8toq.webp',
                sopChoice: null,
            },
            {
                id: '114',
                name: 'Odogaron',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057973/SOP-Moms/MHW/xnzsm77ud9laodmgrvcd.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130472/MHW/ian9mqx0tqhv76vkzv0u.webp',
                sopChoice: null,
            },
            {
                id: '115',
                name: 'Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058010/SOP-Moms/MHW/sfjwz2pqkfa5oytrbzxr.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130503/MHW/bcayxbsduzdrurmdqojk.webp',
                sopChoice: null,
            },
            {
                id: '116',
                name: 'Diablos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/rwbgkzdorpudj6ocn1yi.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130461/MHW/wj2b7shehkb8z1brtgps.png',
                sopChoice: null,
            },
            {
                id: '117',
                name: 'Zorah Magdaros',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057972/SOP-Moms/MHW/hfqxhbbfoxxud5wvgihm.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130470/MHW/emgbqbjdpst5flmzccli.webp',
                sopChoice: null,
            },
            {
                id: '118',
                name: 'Dodogama',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057979/SOP-Moms/MHW/ogyc4hkc8k10bt026mh5.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130478/MHW/k4ts77f6l828l8bhxp7f.webp',
                sopChoice: null,
            },
            {
                id: '119',
                name: 'Lavasioth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/ueycg8oswn6dfxe78nh7.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130481/MHW/xw8he5wuxgu5velxy9yn.png',
                sopChoice: null,
            },
            {
                id: '120',
                name: 'Uragaan',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057968/SOP-Moms/MHW/ea6vs5xhntdmpp7e2az5.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130467/MHW/joaspxhfiqnye6uhmm9u.png',
                sopChoice: null,
            },
            {
                id: '121',
                name: 'Azure Rathalos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057963/SOP-Moms/MHW/nssfzwxfwkthaulngpae.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130461/MHW/xejjnd1q8apjs1ps91mp.webp',
                sopChoice: null,
            },
            {
                id: '122',
                name: 'Bazelgeuse',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/d97vyqog3itfmzglytxp.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130467/MHW/f2whyanbtszduvzsg3pu.webp',
                sopChoice: null,
            },
            {
                id: '123',
                name: 'Black Diablos',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057990/SOP-Moms/MHW/apm1eh9oyfrpgu596g90.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130487/MHW/yplzjqhllea0kuutfnnw.webp',
                sopChoice: null,
            },
            {
                id: '124',
                name: 'Kirin',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057992/SOP-Moms/MHW/txvwl1fzoicolun7nnwu.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130490/MHW/bfkugcostdztrxrqx1eh.png',
                sopChoice: null,
            },
            {
                id: '125',
                name: 'Nergigante',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/pxjdchlazs472b2txodc.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130497/MHW/j7milf3livwqek1uhlkb.webp',
                sopChoice: null,
            },
            {
                id: '126',
                name: 'Teostra',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/wntiugx2ov8dbtly46it.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130461/MHW/oqd0e71fljirza7w7xpf.webp',
                sopChoice: null,
            },
            {
                id: '127',
                name: 'Kushala Daora',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057960/SOP-Moms/MHW/gh5psmeudul3j3wdnvb6.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130460/MHW/ybyarwrca750opii2yyj.webp',
                sopChoice: null,
            },
            {
                id: '128',
                name: 'Deviljho',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058001/SOP-Moms/MHW/wabbxaonypsojinftttz.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130501/MHW/wfuzpctxgz534tm456ga.webp',
                sopChoice: null,
            },
            {
                id: '129',
                name: 'Pink Rathian',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057996/SOP-Moms/MHW/anrjraqsgdgtavgqhuqa.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130496/MHW/tp32qjfaqhfvzod41m2r.webp',
                sopChoice: null,
            },
            {
                id: '130',
                name: 'Vaal Hazak',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057965/SOP-Moms/MHW/wcttazbpshg2imb3ebjz.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130464/MHW/nmzc89tded9hvvxy1ze3.webp',
                sopChoice: null,
            },
            {
                id: '131',
                name: `Xeno'jiiva`,
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057989/SOP-Moms/MHW/efrpyfsajglmc9ylzxea.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130485/MHW/tamcsbhsukmesydobbdk.webp',
                sopChoice: null,
            },
            {
                id: '132',
                name: 'Kulve Taroth',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/brgsrb2rnx4owwjbpljn.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130481/MHW/wjse78ladkqjfypxj1jq.webp',
                sopChoice: null,
            },
            {
                id: '133',
                name: 'Lunastra',
                game: 'MHW',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057973/SOP-Moms/MHW/toxsq2pb8oxen4ebqn6j.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130472/MHW/kay2gcg1mumfh18e1ynb.webp',
                sopChoice: null,
            },
            {
                id: '134',
                name: 'Beotodus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057993/SOP-Moms/MHW/mzxrrkrkrrrtcwtpq61n.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130489/MHW/oqltcfvo5motwfbxedoe.png',
                sopChoice: null,
            },
            {
                id: '135',
                name: 'Banbaro',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057978/SOP-Moms/MHW/knavedswu2olhzlblru6.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130476/MHW/ejspyo1cgqg7fhpbsjsq.webp',
                sopChoice: null,
            },
            {
                id: '136',
                name: 'Viper Tobi-Kadachi',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057982/SOP-Moms/MHW/upbzrvzom1gdjjlabwhi.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130480/MHW/zjiti49zdubiwtwe92nx.webp',
                sopChoice: null,
            },
            {
                id: '137',
                name: 'Nightshade Paolumu',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/kzjhv0w9gpuku8outrxo.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130483/MHW/dk9gjicpk5nb8jde01xz.webp',
                sopChoice: null,
            },
            {
                id: '138',
                name: 'Coral Pukei-Pukei',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057977/SOP-Moms/MHW/khk2so82cm7hglittnv0.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130476/MHW/yo0pizuliccbnusplxq4.webp',
                sopChoice: null,
            },
            {
                id: '139',
                name: 'Barioth',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058007/SOP-Moms/MHW/wytubvem8knd942ejxnt.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130499/MHW/r2zaf0kli2rygzsgep0x.png',
                sopChoice: null,
            },
            {
                id: '140',
                name: 'Nargacuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057983/SOP-Moms/MHW/vdryrvuoogu8ljqmz2lo.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130480/MHW/caio4fkhxm4qcrp7rtps.webp',
                sopChoice: null,
            },
            {
                id: '141',
                name: 'Glavenus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/e9yyyf0guuf412qortbl.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130502/MHW/vjbdtzo0e7mb9cuxy5sn.png',
                sopChoice: null,
            },
            {
                id: '142',
                name: 'Tigrex',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057982/SOP-Moms/MHW/euujllqt4z53rrsy6lf9.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130481/MHW/rot597hcnm5pkaa1eq42.webp',
                sopChoice: null,
            },
            {
                id: '143',
                name: 'Brachydios',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/nwmnf0892uxh2hcdlily.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130494/MHW/rbpy1d1to4qojyiedrzz.png',
                sopChoice: null,
            },
            {
                id: '144',
                name: 'Shrieking Legiana',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058000/SOP-Moms/MHW/ieqrjyjmnhg52oq2tdz4.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130500/MHW/pdyjbcaiy2mv61j2ldqx.webp',
                sopChoice: null,
            },
            {
                id: '145',
                name: 'Fulgur Anjanath',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057970/SOP-Moms/MHW/yyv2rt0dis9flofgkiyu.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130474/MHW/mjjvf9znrycwluacdysj.png',
                sopChoice: null,
            },
            {
                id: '146',
                name: 'Acidic Glavenus',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/lqhdbqvzqtzjnsd6zkc7.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130496/MHW/edkttfmsaeieuhzrhdzs.webp',
                sopChoice: null,
            },
            {
                id: '147',
                name: 'Ebony Odogaron',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057987/SOP-Moms/MHW/ngy0imrfifvag0h6sksx.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130479/MHW/tpedtaix9y4rtqv4nubt.png',
                sopChoice: null,
            },
            {
                id: '148',
                name: 'Velkhana',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/ilxhepo4wxyqsygjhysw.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130494/MHW/zokdqihk9sthqo3q8k7y.webp',
                sopChoice: null,
            },
            {
                id: '149',
                name: 'Seething Bazelgeuse',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057990/SOP-Moms/MHW/mjzow5crjzgtpjox8cvu.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130484/MHW/rkdqrupyrfi0ct3lqmdt.webp',
                sopChoice: null,
            },
            {
                id: '150',
                name: 'Blackveil Vaal Hazak',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058001/SOP-Moms/MHW/d7pvixjwxwkl0lssgzfa.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130503/MHW/quer0bauc68xsknklcuf.webp',
                sopChoice: null,
            },
            {
                id: '151',
                name: 'Namielle',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057967/SOP-Moms/MHW/zhr1m5l0edn4rskwaxpy.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130465/MHW/emgeubiilvvy1af0yont.png',
                sopChoice: null,
            },
            {
                id: '152',
                name: 'Savage Deviljho',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058003/SOP-Moms/MHW/i2b5fjeuyb675ig7ecz6.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130503/MHW/w1m2r0ytfnfgzdzotyoc.webp',
                sopChoice: null,
            },
            {
                id: '153',
                name: 'Ruiner Nergigante',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057993/SOP-Moms/MHW/ilkjbfxyqmnod4avbaim.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130492/MHW/klogagwgmxedm1j50r0z.webp',
                sopChoice: null,
            },
            {
                id: '154',
                name: 'Shara Ishvalda',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057979/SOP-Moms/MHW/spnsvsun3fbdrffz9g2b.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130476/MHW/diytv21hc4kyivffxe5y.webp',
                sopChoice: null,
            },
            {
                id: '155',
                name: 'Zinogre',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058007/SOP-Moms/MHW/z7qy3tc9wxkbnu8hidha.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130506/MHW/lohp6heahekt0ukef6vp.webp',
                sopChoice: null,
            },
            {
                id: '156',
                name: 'Yian Garuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057989/SOP-Moms/MHW/yxvrneumy2mui8t5j8ae.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130485/MHW/edjxoinixd69ipe9gaub.png',
                sopChoice: null,
            },
            {
                id: '157',
                name: 'Scarred Yian Garuga',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057974/SOP-Moms/MHW/tlg3eozc2cdgbj9j5stb.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130470/MHW/fcg6kudepuf1hlpl4iud.webp',
                sopChoice: null,
            },
            {
                id: '158',
                name: 'Silver Rathalos',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057995/SOP-Moms/MHW/fpvvwbdvd9ao24tp6onj.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130494/MHW/s0xpmizky9ionjhwuswy.webp',
                sopChoice: null,
            },
            {
                id: '159',
                name: 'Gold Rathian',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057962/SOP-Moms/MHW/azxfpafejevzmmrnf9hb.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130461/MHW/wgnoj2kiwkogjkbdcuxd.webp',
                sopChoice: null,
            },
            {
                id: '160',
                name: 'Brute Tigrex',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057991/SOP-Moms/MHW/loslczts8ctv4p7uctps.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130487/MHW/gyfq7un2muabzcpm099a.webp',
                sopChoice: null,
            },
            {
                id: '161',
                name: 'Frostfang Barioth',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057964/SOP-Moms/MHW/wp2huq6rzldzx70k3f5w.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130463/MHW/psrn7qo8rs31b9sm3gkf.png',
                sopChoice: null,
            },
            {
                id: '162',
                name: 'Stygian Zinogre',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057984/SOP-Moms/MHW/xlkvbqvo4i0yatld96sb.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130481/MHW/kzfnshq1pbokjbqh4wf7.webp',
                sopChoice: null,
            },
            {
                id: '163',
                name: 'Rajang',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057994/SOP-Moms/MHW/aur27oc6plg7zj5jlhcf.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130494/MHW/rti4y90qa8dxtqgzjfcw.webp',
                sopChoice: null,
            },
            {
                id: '164',
                name: 'Furious Rajang',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057999/SOP-Moms/MHW/p9nujmgumpcewsmpafcg.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130502/MHW/iibhxj6adxd8b9fjnjtv.webp',
                sopChoice: null,
            },
            {
                id: '165',
                name: 'Raging Brachydios',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057971/SOP-Moms/MHW/fa6qspumfe0pahh09ktw.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130470/MHW/layn2u6uo80rike94rrt.webp',
                sopChoice: null,
            },
            {
                id: '166',
                name: `Safi'jiiva`,
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057963/SOP-Moms/MHW/arhdnutwae4rkwrxyyql.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130464/MHW/a8pb8vfzgy8mhugmn6aa.webp',
                sopChoice: null,
            },
            {
                id: '167',
                name: 'Alatreon',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740057991/SOP-Moms/MHW/wrvn67srvuvl9ca4l1yc.webp',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130491/MHW/uh81zj4pfjmc1d9ckz0w.webp',
                sopChoice: null,
            },
            {
                id: '168',
                name: 'Fatalis',
                game: 'MHWIB',
                // iconImg: 'https://res.cloudinary.com/dwdt2yrid/image/upload/v1740058004/SOP-Moms/MHW/ouahwwgt374inslgv60j.png',
                iconImg: 'https://res.cloudinary.com/dkmon6mc6/image/upload/v1742130460/MHW/ybyarwrca750opii2yyj.webp',
                sopChoice: null,
            },
            {
                id: '169',
                name: "Malfestio",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052757/SOP-Moms/MHGen/jjfbpod2jaltsfslk940.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207193/MHGen/v32hqbvnjj0kkom8af1v.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '170',
                name: "Rey Dau",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052801/SOP-Moms/Wilds/ytnndxnkgrj3pnlfwjlp.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207230/Wilds/dy7t5gdcq3qeegjmw38v.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '171',
                name: "Ahtal-Ka",
                game: "MHGU",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052786/SOP-Moms/MHGU/o1nbdnecmrupyda8yqtv.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207197/MHGU/f7zh4kjamv2jqrrxirzh.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '172',
                name: "Shen Gaoren",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052779/SOP-Moms/MHF2/qhvxjndrtlrsj6mfy8jc.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207185/MHF2/f9mypluh9mljf5iipwao.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '173',
                name: "Arkveld",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052803/SOP-Moms/Wilds/wiwjvv76zvrb3qk23lma.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207232/Wilds/elrqfulgxvybjvdk3fil.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '174',
                name: "Nibelsnarf",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052748/SOP-Moms/MH3U/v7fbuppv6dv6dobo0ltj.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207172/MH3U/tjhl3md9gajxzkoos3vz.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '175',
                name: "Ceadeus",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052749/SOP-Moms/MH3/pev2mhelb6ncjzjmelpp.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207167/MH3/sbzy2trvko8juggyabfs.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '176',
                name: "Lala Barina",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052802/SOP-Moms/Wilds/v7ehwfh47d2k9denok6m.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207236/Wilds/hr1fecntwoj6kuvuwain.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '177',
                name: "Royal Ludroth",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH3/kkal9ju4nmjlml0ukbri.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207183/MH3/sibec5jtqtlnyk86ao2e.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '178',
                name: "Shogun Ceanataur",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052755/SOP-Moms/MHF2/hwxzcbumovyso8ju9y8j.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207189/MHF2/u7kmteamfloqc18blz5z.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '179',
                name: "Congalala",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052755/SOP-Moms/MHF2/hisnjffnryxjlu6qrwjp.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207190/MHF2/jj331jocjfev1ydjmg8w.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '180',
                name: "Lao-Shan Lung",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/bgqsvg8y43eia62vwwqd.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/lo7qvvzsnthpvxd2dwbf.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '181',
                name: "Cephadrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052742/SOP-Moms/MH1/u6cknsflsrhbp73jdjta.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207163/MH1/ecet622ecejnsanqra7h.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '182',
                name: "Basarios",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/kswobtmjvdckihlalopu.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207163/MH1/anenlcgrhrjgl5nu1i6b.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '183',
                name: "Duramboros",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052749/SOP-Moms/MH3U/udpfnkmxd8zg4yvshso2.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207170/MH3U/tgdhnbltpyxhly9hg3on.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '184',
                name: "Chameleos",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052782/SOP-Moms/MHF2/dh0iqekcbzlw7qx78eg1.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207190/MHF2/umep8kttpx1achrrafv3.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '185',
                name: "Dalamadur",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052784/SOP-Moms/MH4U/ounhphrw7qtgfi5udqup.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207183/MH4U/qjbux4yde1ou7nkop13t.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '186',
                name: "Mizutsune",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052790/SOP-Moms/MHGen/hlfjaiodl1dwrcv5zlu9.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207204/MHGen/wctghvi3qdpcuobunue9.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '187',
                name: "Dah'ren Mohran",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052774/SOP-Moms/MH4U/ibzgawyuic9e0rfqh06h.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207177/MH4U/urqbfslm1ninnrv1qmtq.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '188',
                name: "Malzeno",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052763/SOP-Moms/MHRiseSB/wgpmd06lgqi6wrvznbms.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207211/MHRiseSB/r4qwmqyccj32okfw8htf.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '189',
                name: "Tetranadon",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052794/SOP-Moms/MHRise/m8wky6nbl6fwgsnclqzq.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207206/MHRise/fevef4bqdghqehcmlvdp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '190',
                name: "Espinas",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRiseSB/gkd6d4xjreafb4hmc1c5.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207210/MHRiseSB/niixqbpsbgxt0zl2nd5w.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '191',
                name: "Seltas",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH4U/nxbgtqykaivjxojeb4tp.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207178/MH4U/jc5gkbaipjpcrduex8my.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '192',
                name: "Magnamalo",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052790/SOP-Moms/MHRise/x1g3dxfxkn7hoekz2rgj.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207203/MHRise/a5hvv4c3uolzmaqfywfd.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '193',
                name: "Gammoth",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052758/SOP-Moms/MHGen/wtjxdkimpdeme5ynezaj.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207193/MHGen/bzpqdc76na3fhali2o0k.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '194',
                name: "Astalos",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052761/SOP-Moms/MHGen/ms0uergz6ylsykgexiyf.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207195/MHGen/dmwgptvoil7oblg1bf4h.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '195',
                name: "Garangolm",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052796/SOP-Moms/MHRiseSB/nch0seunba9oam6lgdjm.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207210/MHRiseSB/fvuu3vdb0ba1jree59og.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '196',
                name: "Nerscylla",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH4U/pgq3aswb2khn2jyvfazt.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207177/MH4U/vgjru21loe22s8w6pzbx.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '197',
                name: "Yian Kut-Ku",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/mgbssmtcluglrzki86qa.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/jgd0gq5ftxsimpwrqsfq.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '198',
                name: "Gobul",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052746/SOP-Moms/MH3/bwktsexlynxhcg22s48c.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207167/MH3/sqkna7slhile7oiizapq.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '199',
                name: "Iodrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/o3czljzqej5ryacqbtoq.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/eivkje8lnrwnmqj9gfan.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '200',
                name: "Ajarakan",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052806/SOP-Moms/Wilds/p6m5fyldumgxf8thkusk.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207237/Wilds/hrpexsjia9ie0phqnqad.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '201',
                name: "Lagombi",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052783/SOP-Moms/MH3U/f6ibq3cy2ysruslwveum.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207183/MH3U/ro7zhep2x3ygtxzhah0k.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '202',
                name: "Crimson Fatalis",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052780/SOP-Moms/MHF2/vpkwtw8nv3aptrkqsd8l.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207186/MHF2/ssenvhdkcyuz3rxbfmta.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '203',
                name: "Seltas Queen",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052752/SOP-Moms/MH4U/qkrhvrmtjggoqtpnsdw5.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207178/MH4U/j4zwtdq6da9tej8ncur5.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '204',
                name: "Akantor",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052764/SOP-Moms/MHF2/wssq7zknnlgscjyhd0hs.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207191/MHF2/z0bhgaqaptdsa6xqzga8.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '205',
                name: "Seregios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MH4U/s42sse6xhvyhffzq0mg4.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207187/MH4U/e69u9toj6vgzygate6wl.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '206',
                name: "Quematrice",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/Wilds/vszjgbtrsufquj0b5oag.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207234/Wilds/asq6uldujedouoapaj50.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '207',
                name: "Plesioth",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/i1ny8ywc8n4tmtvurrcy.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/orghlxqrqsfguofocyvy.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '208',
                name: "Goss Harag",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052793/SOP-Moms/MHRise/gdvuxveoibbufcjd3le2.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207205/MHRise/amproosunouusowuxjki.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '209',
                name: "Daimyo Hermitaur",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052782/SOP-Moms/MHF2/vzicspwqdpeydjaalvai.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207189/MHF2/x8ojjt2p0l4opnl7zvzm.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '210',
                name: "Valstrax",
                game: "MHGU",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHGU/hgxjqbrc8e3aderi6wvt.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207202/MHGU/tnbftamomwrzxqbdpehf.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '211',
                name: "Great Wroggi",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/MH3U/odmsedq7greirs9zvy85.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207176/MH3U/usjfzh5kxl4m4fzdww4w.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '212',
                name: "Gore Magala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052753/SOP-Moms/MH4U/aejzozhqbbxjdlgfrkvw.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207188/MH4U/mnizygwty6m0wfj6fyfb.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '213',
                name: "Jhen Mohran",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052766/SOP-Moms/MH3/oczzktsbwtmliv7vkffo.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207172/MH3/vpomqffxpsy8ypsjuu5c.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '214',
                name: "Blangonga",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MHF2/dmrr3d1rqfkcpqvrlsvv.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207188/MHF2/sfocdawzh3vuobi1tpaq.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '215',
                name: "Ukanlos",
                game: "MHFU",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052756/SOP-Moms/MHFU/wb7ghfb0s2m5u48x0nxp.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207192/MHFU/ciq2rtbthjgtduynhcar.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '216',
                name: "Gypceros",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052745/SOP-Moms/MH1/cz11lv7rn1mrhlest73s.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/zfgdlwf1y2fd4eu6czu9.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '217',
                name: "Shagaru Magala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052779/SOP-Moms/MH4U/evrd3jdpy25rbbnpjrkm.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207187/MH4U/zlhmwya97z4i9tb2f7ri.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '218',
                name: "Monoblos",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052743/SOP-Moms/MH1/d30iwllbvspdowfahest.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207163/MH1/lewsq4wujngvf8ejitrg.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '219',
                name: "Najarala",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/MH4U/oggfpvv1pelgajzxivrm.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207178/MH4U/kkv501h5twr6mptagz7z.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '220',
                name: "Balahara",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/Wilds/ekiux7o9plnvjkcfet79.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207228/Wilds/zoxmmgex6nz1bnqdfyby.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '221',
                name: "Gogmazios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052752/SOP-Moms/MH4U/oka1o180i8ohujaibm6v.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207183/MH4U/vynsrrabt1bsywrdvobw.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '222',
                name: "Velocidrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052743/SOP-Moms/MH1/rgsvas5wf46gfa2lx2ep.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/agqrtx9531zfvvvkpdxf.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '223',
                name: "Gigginox",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH3/pdccbyqlh3d7dmmcobdz.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207165/MH3/pybrt9owizc5pdytplhl.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '224',
                name: "Zamtrios",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052753/SOP-Moms/MH4U/tcinu1t9u3ofnpw8xdvr.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207181/MH4U/ctjiflgbca4asgqpdemr.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '225',
                name: "Gravios",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/mlwoirjd90jorwltbpws.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/zh6ojduvmhi0xtkyrzmm.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '226',
                name: "Amatsu",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052789/SOP-Moms/MHGen/dykatxsd6uk03jhdwtsj.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207197/MHGen/ehe6gcgdzzmap6a4u8pl.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '227',
                name: "Gaismagorm",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052768/SOP-Moms/MHRiseSB/zfcsywvgpz0k1nu5nfil.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207214/MHRiseSB/u07udsdif5k1ypzm7rg9.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '228',
                name: "Great Baggi",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052760/SOP-Moms/MH3/k3b3bbiku6fkfkz4pyl8.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207173/MH3/fwqoz5h7eg18eghlre1z.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '229',
                name: "Somnacanth",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052793/SOP-Moms/MHRise/cxkdr94ojuwzh3rpo7qm.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207211/MHRise/wqogydvooih4s2ox4r6u.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '230',
                name: "Volvidon",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052770/SOP-Moms/MHGen/f35tyblpuzoxotdhimqh.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207207/MHGen/hac5znqwcy2mnvlhrfbs.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '231',
                name: "Nakarkos",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052784/SOP-Moms/MHGen/sliiftoydfrkshxhcf0n.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207195/MHGen/ddjopftpmx4jgj01ug4q.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '232',
                name: "Thunder Serpent Narwa",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRise/yahop7fishfifowdrphs.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207209/MHRise/ttjvvd5od1ishnsy571z.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '233',
                name: "Qurupeco",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052746/SOP-Moms/MH3/f9izcy0bgmttvfru3mv8.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207168/MH3/bkl4cbkffiymq6ykvul3.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '234',
                name: "Aknosom",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052787/SOP-Moms/MHRise/xaebbowqsmnw4ipwrsyv.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207198/MHRise/dsldo3lazokrcjsesixo.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '235',
                name: "Bishaten",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052763/SOP-Moms/MHRise/untg12k5ei7kz064hxn8.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207201/MHRise/vnyi1nixrbhl0y5wgksc.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '236',
                name: "Khezu",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740090050/SOP-Moms/MHF2/atlupfoap6jyybybcmel.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207185/MHF2/wqrvf4pemco0xxqljtvl.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '237',
                name: "Lunagaron",
                game: "MHRiseSB",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052798/SOP-Moms/MHRiseSB/mgzdtkrtvkrwww8qlpb7.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207211/MHRiseSB/quyjmaj7hplr93ngpwmp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '238',
                name: "Agnaktor",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052750/SOP-Moms/MH3/zt6obchnxewoedqprmie.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207167/MH3/oe7yv4qqn6dxikigvlsl.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '239',
                name: "Almudron",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052764/SOP-Moms/MHRise/nt4t71bdyzlpv3jfyjng.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207205/MHRise/x5q1hgzjj5gurm5qm0kp.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '240',
                name: "Bulldrome",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MHF2/yrotqh27n0ckrmgrxsnq.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207188/MHF2/soqzdo2lw9ksmzubzoyy.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '241',
                name: "White Fatalis",
                game: "MHF2",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052780/SOP-Moms/MHF2/efcvhzjogjucbzrgkpbe.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207186/MHF2/o3fugdztlcsw4wfvwm3l.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '242',
                name: "Kecha Wacha",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052751/SOP-Moms/MH4U/ukpelc3aszatrizomhdg.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207176/MH4U/mtqs6j93wyymbtbxfrod.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '243',
                name: "Doshaguma",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052797/SOP-Moms/Wilds/eahkrjzuiybe1mmyvm3v.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207227/Wilds/a6z7iapmcp2aruq6bfz9.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '244',
                name: "Rakna-Kadaki",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHRise/he9h8xasox08n1wka52l.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207208/MHRise/e4nk9of0s6cexj2djk4q.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '245',
                name: "Lagiacrus",
                game: "MH3",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052748/SOP-Moms/MH3/xq67wlyoinm9ekcjeean.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207168/MH3/bgxcx9f6hqvbwqpumbku.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '246',
                name: "Rompopolo",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052802/SOP-Moms/Wilds/ll1mzqn8tsokt8hffl99.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207234/Wilds/xv5un36e2mbbedxsn4uv.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '247',
                name: "Arzuros",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052771/SOP-Moms/MH3U/nhjlgvwhhp1co7vkuydn.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207174/MH3U/kjfag6idh5joof7ysbnu.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '248',
                name: "Dire Miralis",
                game: "MH3U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052754/SOP-Moms/MH3U/hpgqyr4knjmz9fahdmwi.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207168/MH3U/ahf2zj5xgdpbwimkedho.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '249',
                name: "Tetsucabra",
                game: "MH4U",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MH4U/xcefmdipaymmwzpmylxl.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207192/MH4U/cm92tv0o2siahke6m2ah.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '250',
                name: "Great Maccao",
                game: "MHGen",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052783/SOP-Moms/MHGen/dxbqjiwsp0yae3ocwovy.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207192/MHGen/fb8ka6ewsmqrgzrnytgg.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '251',
                name: "Yama Tsukami",
                game: "MHFU",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052758/SOP-Moms/MHFU/wqdiq9dqksqnwck5msuu.webp",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207192/MHFU/zmlvqtlvd3tdkeeqihs7.webp",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '252',
                name: "Gendrome",
                game: "MH1",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052744/SOP-Moms/MH1/ceq6xot9cpso1vosbpkd.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207164/MH1/cdajohnrrd7cxrejl57v.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '253',
                name: "Uth Duna",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052776/SOP-Moms/Wilds/qsv4ydjxlthntbdznota.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207239/Wilds/s7xjcbgzosmfubwsw5v8.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '254',
                name: "Chatacabra",
                game: "Wilds",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052797/SOP-Moms/Wilds/cbpsb0lg0vedebhai5hl.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207227/Wilds/ckpzkgvsxnppnaecpcc0.png",
                sopChoice: null,
                isHidden: true,
            },
            {
                id: '255',
                name: "Wind Serpent Ibushi",
                game: "MHRise",
                // iconImg: "https://res.cloudinary.com/dwdt2yrid/image/upload/v1740052795/SOP-Moms/MHRise/lpwhdeotfvtrolycbso9.png",
                iconImg: "https://res.cloudinary.com/dbk9pzhp9/image/upload/v1742207208/MHRise/pvqkastk1iufrsfrt0t8.png",
                sopChoice: null,
                isHidden: true,
            },
        ]
        utilService.saveToStorage(STORAGE_KEY, monsters)
    }
}

// TEST DATA
// storageService.post(STORAGE_KEY, {vendor: 'Subali Rahok 2', price: 980}).then(x => console.log(x))

// add imaage loader?
// change extra challenge css?
// test site 
